version: "3.8"
services:

  marquez:
    image: marquezproject/marquez:0.50.0
    environment:
      - POSTGRES_HOST=marquez-postgres
      - POSTGRES_PORT=5432
      - SEARCH_ENABLED=false
    expose:
      - "5000"
      - "5001"
    volumes:
      - ./wait-for-it.sh:/usr/src/app/wait-for-it.sh
      - marquez-data:/opt/marquez
    entrypoint: ["./wait-for-it.sh", "marquez-postgres:5432", "--", "./entrypoint.sh"]
#    # Enables SQL statement logging (see: https://www.postgresql.org/docs/12/runtime-config-logging.html#GUC-LOG-STATEMENT)
#    # command: ["postgres", "-c", "log_statement=all"]
    networks:
      - mssdk-network

  marquez-web:
    image: marquezproject/marquez-web:0.50.0
    environment:
      - MARQUEZ_HOST=marquez
      - MARQUEZ_PORT=5000
      - WEB_PORT=3000
    expose:
      - "3000"
    depends_on:
      - marquez
    networks:
      - mssdk-network

  marquez-postgres:
    image: postgres:13
    expose:
      - "5432"
    environment:
      POSTGRES_USER: ${MARQUEZ_DB_USER}
      POSTGRES_PASSWORD: ${MARQUEZ_DB_PASSWORD}
      POSTGRES_DB: ${MARQUEZ_DB_NAME}
    volumes:
      - marquez-postgres-data:/var/lib/postgresql/data
    networks:
      - mssdk-network

volumes:
  marquez-data:
  marquez-postgres-data:

networks:
  mssdk-network:
    driver: bridge
