version: '3'
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    labels:
      breeze.description: "Integration required for OTEL/opentelemetry hooks."
    command: [ --config=/etc/otel-collector-config.yml ]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    expose:
      - "4318"
    networks:
      - mssdk-network

networks:
  mssdk-network:
    driver: bridge
