from pathlib import Path

TESTS_PATH = Path(__file__).parent.resolve()

TEST_DATA_PATH = TESTS_PATH / "test_data"

TEST_DATA_EXAMPLE_MAPPING_PACKAGES_PATH = TEST_DATA_PATH / "example_mapping_packages"
TEST_DATA_EXAMPLE_MAPPING_PACKAGE_EFORMS_29_V1_8_ZIP_PATH = TEST_DATA_EXAMPLE_MAPPING_PACKAGES_PATH / "package_eforms_29_v1.8.zip"

TEST_DATA_EXAMPLE_NOTICES_PATH = TEST_DATA_PATH / "example_notices"
TEST_DATA_EXAMPLE_NOTICES_373731_2024_XML_PATH = TEST_DATA_EXAMPLE_NOTICES_PATH / "373731-2024.xml"

TEST_DATA_EXAMPLE_RDF_PATH = TEST_DATA_PATH / "example_rdf"
TEST_DATA_EXAMPLE_RDF_373731_2024_XML_PATH = TEST_DATA_EXAMPLE_RDF_PATH / "373731-2024.rdf.ttl"
